hackharvard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from .views import *


app_name = 'main'

urlpatterns = [
    path('', QuizListView.as_view(), name='home'),
    path('assignment/<pk>/', AssignmentPage, name='assignment-view'),
    path('assignment/<pk>/data/', assignment_data_view, name='assignment-data-view'),
    path('leaderboard/', LeaderBoardPage, name='leaderboard'),
    path('assignment/<pk>/save/', save_quiz_view, name='save-view'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import random
# Create your models here.

class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tokens = models.IntegerField()


class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of quiz")

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        return self.question_set.all()[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizzes'
    
class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()


class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)
    

main/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import ListView
from .models import *

# Create your views here.
class QuizListView(ListView):
    model = Quiz
    template_name = 'main/home.html'

def AssignmentPage(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    context = {'obj': quiz}
    return render(request, 'main/assignment.html', context)

def assignment_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)
        return JsonResponse({'score': score_, 'results': results})
       

def LeaderBoardPage(request):
    context = {}
    return render(request, 'main/leaderboard.html', context)

main/templates/main/assignment.html
{% extends 'main/base.html' %}
{% load static %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}
{{obj.name}}
<hr>
<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type = "submit" class="btn btn-primary mt-3">save</button>
</form>
{% endblock content %}

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href={% static 'style.css' %}>

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

main/templates/main/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    
    <meta charset = "UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

	<link rel = "stylesheet" href = "{% static 'css/list.css' %}">

    <script src="{% static 'js/main.js' %}" defer></script>

</head>
<body style="display:flex;" background="1.jpg" link="#000" alink="#017bf5" vlink="#000">
	<br />
	<left><a href="{% url 'main:home' %}"><img src="https://media-exp1.licdn.com/dms/image/C4E03AQH9ROVNalOLrg/profile-displayphoto-shrink_200_200/0/1632606177293?e=1638403200&v=beta&t=WuOzKW5E8BeUM_QfrjJMRVFte_RTzBHFvUFTiVGTi00" alt=""></a></left>
    <p>Hello, {{name}}    Tokens: {{token}}</p>
	<br /><br />
	<h3 style = "justify-content:center">
            <p><a href="{% url 'main:leaderboard' %}">Class Leaderboard</a></p>
            <p><a href="{% url 'main:leaderboard' %}">Shop</a></p>
	</h3>
  
  <!-- Modal -->
  <div class="modal fade" id="startModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

  <h3>
    <div class = "box">
        <link rel = "stylesheet" href = "{% static 'css/list.css' %}">
        <h2>List of Assignments</h2>
        <ul>
            {% for obj in object_list %}
            <li><span>1</span><button
                class="btn btn-link modal-button"
                data-pk="{{obj.pk}}"
                data-quiz="{{obj.name}}"
                data-toggle="modal"
                data-target="#startModal">
                {{obj.name}}</li>
            {% endfor %}
    </div>
</h3>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/leaderboard.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> 
    
    <meta name="viewport" content="width=device-width, initial-scale=1, 
    maximum-scale=1, minimum-scale=1" />

</head>

<div class="gif">
	<img src="https://3dtext2gif.com/exported_stickers/_3dtext2gif_aalhhxrcbqdy.gif" alt="This will display an animated GIF" style="justify-content:center;"/>
</div>

<div class="wrapper">
	<div class="lboard_section">
		<div class="lboard_tabs">
		</div>
		<div class="lboard_wrap">
			<div class="lboard_item displayed" style="display: block;">
				<div class="lboard_mem">
					<div class="img">
						<img src="https://cdn.discordapp.com/attachments/749420152734351424/896612176666722354/Untitled.png" alt="picture_2">
					</div>
					<div class="name_bar">
						<p><span>1.</span> Alex Mike</p>
						<div class="bar_wrap">
							<div class="inner_bar" style="width: 95%"></div>
						</div>
					</div>
					<div class="points">
						1195 points
					</div>
				</div>
				<div class="lboard_mem">
					<div class="img">
						<img src="https://cdn.discordapp.com/attachments/749420152734351424/896612178398953472/fdsfsadf.png" alt="picture_3">
					</div>
					<div class="name_bar">
						<p><span>2.</span>Johnson</p>
						<div class="bar_wrap">
							<div class="inner_bar" style="width: 80%"></div>
						</div>
					</div>
					<div class="points">
						1185 points
					</div>
				</div>
				<div class="lboard_mem">
					<div class="img">
						<img src="https://cdn.discordapp.com/attachments/749420152734351424/896612179581730866/4tjinfisnf.png" alt="picture_1">
					</div>
					<div class="name_bar">
						<p><span>3.</span>Charles John</p>
						<div class="bar_wrap">
							<div class="inner_bar" style="width: 70%;"></div>
						</div>
					</div>
					<div class="points">
						1160 points
					</div>
				</div>
				<div class="lboard_mem">
					<div class="img">
						<img src="https://cdn.discordapp.com/attachments/749420152734351424/896617923664310332/eafvadfdad.png" alt="picture_5">
					</div>
					<div class="name_bar">
						<p><span>4.</span>Scarlett Angela</p>
						<div class="bar_wrap">
							<div class="inner_bar" style="width: 50%"></div>
						</div>
					</div>
					<div class="points">
						1130 points
					</div>
				</div>
				<div class="lboard_mem">
					<div class="img">
						<img src="https://cdn.discordapp.com/attachments/749420152734351424/896617925115543552/dassadasd.png" alt="picture_4">
					</div>
					<div class="name_bar">
						<p><span>5.</span>Rosey</p>
						<div class="bar_wrap">
							<div class="inner_bar" style="width: 30%"></div>
						</div>
					</div>
					<div class="points">
						1110 points
					</div>
				</div>
			</div>
		</div>
	</div>
</div>	


<script src="{% static 'scripts.js' %}"></script>
<body>
    
</body>
</html>

main/templates/main/shop.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset = "UTF-8">
	<title>
	</title>
</head>
<body style="background-color:#25bcff">
	<br /> 
    <font face="Lato" color=rgb(27,67,94) size="7">
        <left>Shop</left>
        <center>Tokens: {{token}}</center>
    </font>
	<h1 align="left">
		<font face="Lato" color=rgb(27,67,94) size="7">
			Avatars
			<br /><br />
			Costs 1 Token: <a href="https://www.linkedin.com/in/ben-shi-115a89200/"><img src="https://cdn.discordapp.com/attachments/749420152734351424/896612176666722354/Untitled.png" alt=""></a>
			<br /><br />
			Costs 5 Tokens: <a href="https://www.linkedin.com/in/ben-shi-115a89200/"><img src="https://cdn.discordapp.com/attachments/749420152734351424/896612178398953472/fdsfsadf.png" alt=""></a>
			<br /><br />
			Costs 10 Tokens: <a href="https://www.linkedin.com/in/ben-shi-115a89200/"><img src="https://cdn.discordapp.com/attachments/749420152734351424/896612179581730866/4tjinfisnf.png" alt=""></a>
		</font>
	</h1>

	<style>
		html 
			{
				height: 110%;
			}
		body 
			{
				background-image: linear-gradient(#FFFFFF, rgb(37, 188, 255));
			}
		</style>

</body>
</html>